config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :highlights

  root to: 'highlights#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation) }
  end

end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]


  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.all
  end

  # GET /highlights/1
  # GET /highlights/1.json
  def show
  end

  # GET /highlights/new
  def new
    @highlight = Highlight.new
  end

  # GET /highlights/1/edit
  def edit
  end

  # POST /highlights
  # POST /highlights.json
  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to @highlight, notice: 'Highlight was successfully created.' }
        format.json { render :show, status: :created, location: @highlight }
      else

        format.html { render :new }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to @highlight, notice: 'Highlight was successfully updated.' }
        format.json { render :show, status: :ok, location: @highlight }
      else
        format.html { render :edit }
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highlights/1
  # DELETE /highlights/1.json
  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html { redirect_to highlights_url, notice: 'Highlight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/views/highlights/_form.html.erb
<%= form_for(@highlight) do |f| %>
  <% if @highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% @highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing highlight</h1>

<%= render 'form' %>

<%= link_to 'Show', @highlight %> |
<%= link_to 'Back', highlights_path %>

app/views/highlights/index.html.erb
<h1>Listing highlights</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%= highlight.title %></td>
        <td><%= highlight.description %></td>
        <td><%= link_to 'Show', highlight %></td>
        <% if(user_signed_in?) %>
            <td><%= link_to 'Edit', edit_highlight_path(highlight) %></td>
            <td><%= link_to 'Destroy', highlight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Highlight', new_highlight_path %>
<% end %>

app/views/highlights/new.html.erb
<h1>New highlight</h1>

<%= render 'form' %>

<%= link_to 'Back', highlights_path %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @highlight.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @highlight.description %>
</p>

<%= link_to 'Edit', edit_highlight_path(@highlight) %> |
<%= link_to 'Back', highlights_path %>

app/views/layouts/_header.html.erb
<ul class="nav pull-right">

  <% if user_signed_in? %>
      <li id="fat-menu" class="dropdown">

        <ul class="dropdown-menu">
          <li><%= link_to "Profile", edit_user_registration_path %></li>


        </ul>
      </li>
      <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
  <% else %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Afar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <%= render "layouts/header" %>

  <div id="container">
    <%= yield %>
  </div>>


</body>
</html>

app/views/layouts/header.html.erb
<ul class="nav pull-right">
  <li><%= link_to "Home",       root_path %></li>
  <li><%= link_to "Help",         help_path %></li>
  <% if user_signed_in? %>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        </li>
      </ul>
    </li>
    <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
  <% end %>
</ul>

app/views/static_pages/home.html.erb
<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>